apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: openshifttemplateservicebroker
    namespace: openshift-template-service-broker
spec:
    channel: "4.2"
    installPlanApproval: Automatic
    name: openshifttemplateservicebroker
    source: redhat-operators
    sourceNamespace: openshift-marketplace